server:
  port: 12345

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/testdb
    username: postgres
    password: 123456
    driverclassname: org.postgresql.Driver

#spring:
#  datasource:
#    url: jdbc:dm://192.168.23.137:5236/TEXT
#    username: SYSDBA
#    password: SYSdba001
#    dialect: org.hibernate.dialect.DmDialect
#    driverclassname: dm.jdbc.driver.DmDriver

#spring:
#  datasource:
#    url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=UAT;trustServerCertificate=true
#    username: sa
#    password: Zzw123456
#    driverclassname: com.microsoft.sqlserver.jdbc.SQLServerDriver

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/dev?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
#    username: root
#    password: 123456
#    driverclassname: com.mysql.cj.jdbc.Driver


#liquibase:
#  diff-column-order: false